import { Hono } from 'hono'
import { APP_META } from '../config/constants.js'
import {
  ANIME_KEYS, MANGA_KEYS, MOVIE_KEYS, NOVEL_KEYS, COMIC_KEYS,
} from '../providers/registry.js'

const router = new Hono()

router.get('/', (c) =>
  c.json({
    ...APP_META,
    status: 'online',
    docs: '/',
    health: '/health',
    sources: {
      anime: ANIME_KEYS,
      manga: MANGA_KEYS,
      movies: MOVIE_KEYS,
      novels: NOVEL_KEYS,
      comics: COMIC_KEYS,
      meta: ['anilist', 'anilist-manga', 'mal', 'tmdb'],
      news: ['animenewsnetwork'],
    },
    endpoints: {
      anime: [
        'GET /anime/sources',
        'GET /anime/search?q=&page=&source=',
        'GET /anime/advanced-search?type=&status=&rated=&score=&season=&language=&sort=&genres=&page=',
        'GET /anime/info?id=&source=',
        'GET /anime/stream?episodeId=&source=&quality=',
        'GET /anime/download?episodeId=&source=&quality=',
        'GET /anime/servers?episodeId=&source=',
        'GET /anime/trending?page=',
        'GET /anime/popular?page=',
        'GET /anime/recent?page=',
        'GET /anime/recently-added?page=',
        'GET /anime/recently-completed?page=',
        'GET /anime/upcoming?page=',
        'GET /anime/subbed?page=',
        'GET /anime/dubbed?page=',
        'GET /anime/movies?page=',
        'GET /anime/tv?page=',
        'GET /anime/ova?page=',
        'GET /anime/ona?page=',
        'GET /anime/specials?page=',
        'GET /anime/spotlight',
        'GET /anime/suggestions?q=',
        'GET /anime/genres-list',
        'GET /anime/studio?studio=&page=',
        'GET /anime/pahe/recent?page=',
      ],
      manga: [
        'GET /manga/sources',
        'GET /manga/search?q=&page=&source=',
        'GET /manga/info?id=&source=',
        'GET /manga/read?chapterId=&source=',
        'GET /manga/popular?page=',
        'GET /manga/recent?page=',
        'GET /manga/latest-updates?page=',
        'GET /manga/random',
        'GET /manga/trending',
        'GET /manga/hot',
        'GET /manga/ranking?type=day|week|month|total',
        'GET /manga/kakalot/genre?genre=&page=',
        'GET /manga/kakalot/latest?page=',
        'GET /manga/suggestions?q=',
      ],
      movies: [
        'GET /movies/sources',
        'GET /movies/search?q=&page=&type=all|western|asian&source=',
        'GET /movies/info?id=&source=',
        'GET /movies/stream?episodeId=&mediaId=&source=&quality=',
        'GET /movies/download?episodeId=&mediaId=&source=&quality=',
        'GET /movies/servers?episodeId=&mediaId=&source=',
        'GET /movies/trending?type=movie|tv',
        'GET /movies/recent?type=movie|tv',
        'GET /movies/genre?genre=&page=&source=',
        'GET /movies/country?country=&page=&source=',
        'GET /movies/spotlight',
        'GET /movies/asian/recent',
        'GET /movies/episode/sources?episodeId=&mediaId=&server=&source=&quality=',
        'GET /movies/random?type=movie|tv',
      ],
      proxy: [
        'GET /proxy/health',
        'GET /proxy/sign?u=&referer=&origin=',
        'GET /proxy/hls?u=&referer=&origin=',
        'GET /proxy/m3u8?u=&referer=&origin=',
        'GET /proxy/segment?u=&referer=&origin=',
      ],
      books: [
        'GET /books/sources',
        'GET /books/novels/search?q=',
        'GET /books/novels/info?id=&chapterPage=',
        'GET /books/novels/read?chapterId=',
        'GET /books/comics/search?q=&page=',
      ],
      meta: [
        'GET /meta/tmdb/search?q=&page=',
        'GET /meta/tmdb/info?id=&type=movie|tv',
        'GET /meta/tmdb/trending?type=&period=day|week&page=',
        'GET /meta/tmdb/stream?id=&quality=',
        'GET /meta/tmdb/download?id=&quality=',
        'GET /meta/anilist/search?q=&page=&perPage=',
        'GET /meta/anilist/advanced-search?...',
        'GET /meta/anilist/info?id=&dub=&fetchFiller=',
        'GET /meta/anilist/info-by-id?id=',
        'GET /meta/anilist/episodes?id=&dub=&fetchFiller=',
        'GET /meta/anilist/trending?page=&perPage=',
        'GET /meta/anilist/popular?page=&perPage=',
        'GET /meta/anilist/recent?provider=Hianime|gogoanime&page=&perPage=',
        'GET /meta/anilist/schedule?...',
        'GET /meta/anilist/genre?genres=&page=&perPage=',
        'GET /meta/anilist/random',
        'GET /meta/anilist/character?id=',
        'GET /meta/anilist/staff?id=',
        'GET /meta/anilist-manga/search?q=&page=&perPage=',
        'GET /meta/anilist-manga/info?id=',
        'GET /meta/mal/search?q=&page=',
        'GET /meta/mal/info?id=',
      ],
      news: [
        'GET /news/topics',
        'GET /news/feeds?topic=',
        'GET /news/info?id=',
      ],
      health: [
        'GET /health',
        'GET /health/anime',
        'GET /health/manga',
        'GET /health/movies',
        'GET /health/books',
        'GET /health/meta',
        'GET /health/news',
      ],
    },
    features: [
      'Automatic multi-source fallback on search endpoints (race + sequential modes)',
      'Built-in HLS m3u8 rewriter and segment proxy with Referer/Origin header injection',
      'Range-request passthrough for MP4 byte-range seeking',
      'In-memory TTL caching with auto-eviction',
      'Per-IP rate limiting that skips preflights and health checks',
      'Quality filtering on stream + download endpoints',
      'Wide-open CORS for any embedding player',
      'X-Frame-Options ALLOWALL for fullscreen iframes',
      'Per-request 28s timeout returning 504 instead of hanging',
      'Powered by @consumet/extensions 1.8.8, Hono 4.12.x, undici 7',
      'Railway / Docker / Nixpacks / Heroku-ready',
    ],
  }),
)

export default router
